---

- name: Generate ssh key if absent
  user:
          name: "{{ ssh_user }}"
          generate_ssh_key: yes
          ssh_key_bits: "{{ ssh_key_bits }}"
  register: result


- name: Collect ssh public key
  set_fact:
          ssh_public_key: "{{ result.ssh_public_key }}"

